db_host: 192.168.56.102
db_port: 3306
db_name: forgejo
db_user: forgejo
db_password: supersecret

lfs_jwt_secret: ZzUyN5vEjtr8QSk10rucI1WiON1QxmKw88uzC4-y4zg
internal_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
oauth2_jwt_secret: duy_SFjm06TRRjXpj-ECOrQIKl_X7kEuGICWqeF97xI
