- name: Configure Forgejo DB
  hosts: db
  become: yes
  roles:
    - db

- name: Configure Forgejo App
  hosts: forgejo
  become: yes
  roles:
    - forgejo

- name: Configure Nginx App
  hosts: nginx
  become: yes
  roles:
    - nginx
