---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - git
    state: present

- name: Create forgejo system user
  user:
    name: git
    home: /home/git
    shell: /bin/bash
    system: yes
    create_home: yes

- name: Ensure /var/lib/forgejo directory exists
  file:
    path: /var/lib/forgejo
    state: directory
    owner: git
    group: git
    mode: '0750'

- name: Ensure /etc/forgejo directory exists
  file:
    path: /etc/forgejo
    state: directory
    owner: root
    group: git
    mode: '0770'

- name: Download Forgejo source archive from GitHub
  get_url:
    url: https://codeberg.org/forgejo/forgejo/releases/download/v11.0.1/forgejo-src-11.0.1.tar.gz
    dest: /tmp/forgejo-src.tar.gz

- name: Extract archive to /opt/
  unarchive:
    src: /tmp/forgejo-src.tar.gz
    dest: /opt/
    remote_src: yes

- name: Rename extracted folder to /opt/forgejo
  command: mv /opt/forgejo-src-11.0.1 /opt/forgejo
  args:
    creates: /opt/forgejo

- name: Download Forgejo release
  get_url:
    url: "https://codeberg.org/forgejo/forgejo/releases/download/v11.0.1/forgejo-11.0.1-linux-amd64"
    dest: /opt/forgejo/forgejo
    mode: '0755'

- name: Create symlink to forgejo binary
  file:
    src: /opt/forgejo/forgejo
    dest: /usr/local/bin/forgejo
    state: link
    force: yes

- name: Ensure /opt/forgejo is owned by git
  file:
    path: /opt/forgejo
    state: directory
    recurse: yes
    owner: git
    group: git

- name: Copy app.ini on Forgejo лњлю
  template:
    src: app.ini.j2
    dest: /etc/forgejo/app.ini
    owner: git
    group: git
    mode: '0644'

- name: Copy Forgejo systemd service
  copy:
    src: forgejo.service
    dest: /etc/systemd/system/forgejo.service
    mode: '0644'

- name: Reload and start Forgejo service
  systemd:
    daemon_reload: yes
    name: forgejo
    enabled: yes
    state: started
