- name: Install MariaDB
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-pymysql
    update_cache: yes

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create forgejo database
  mysql_db:
    name: forgejo
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create forgejo user
  mysql_user:
    name: forgejo
    password: "{{ db_password }}"
    priv: "forgejo.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Allow MariaDB to listen on all interfaces
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  notify: Restart MariaDB
